# Site settings
title: hwp.io
header-img: img/home-bg.jpg
email: hudsonpeden@gmail.com
copyright_name: Hudson W. Peden
description: "Design, Photography, etc."
baseurl: ""
url: "http://hwp.io"
 #twitter_username: SBootstrap
github_username:  hudsonpeden
#facebook_username:  StartBootstrap
email_username:  hudsonpeden@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "contact.html"]

gems: [jekyll-paginate, jekyll-feed]
